# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH 连接至 Actions'
        required: false 
        default: 'false'
env:
  REPO_URL: https://github.com/openwrt/openwrt.git
  REPO_BRANCH: openwrt-22.03


jobs:
  build:
    runs-on: ubuntu-20.04

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone --single-branch $REPO_BRANCH $REPO_URL openwrt
        